language: csharp
solution: "Project 3 - Main/Project 3 - Press Project.sln"
install:
    - msbuild restore "TestPressProject/TestPressProject.csproj"
    - nuget install NUnit.Console -ExcludeVersion
script:
    - msbuild /p Configuration=Debug "TestPressProject/TestPressProject.csproj"