language: csharp
mono: none
dotnet: 3.1
solution: "Project 3 - Main/Project 3 - Press Project.sln"

jobs:
  include:
    - stage: "Build"                
      name: "Building application core"
      script: ./build.sh
    - stage: "Test
      name: "Test application core"
      script: ./test.sh