language: csharp
mono: none
dotnet: 3.1
solution: "Project 3 - Main/Project 3 - Press Project.sln"

jobs:
   include:
     - stage: "build"
       Name: "Build core application on .NET Core 3.1"
       script: 
           - dotnet restore 'Project 3 - Main/Project 3 - Press Project.csproj'
           - dotnet build 'Project 3 - Main/Project 3 - Press Project.csproj'
     - stage: "test"
       Name: "Test core application on .NET Core 3.1"
       script:
           - cd TestPressProject 
           - dotnet add package NUnit.Console
           - dotnet restore TestPressProject.csproj
           - dotnet build TestPressProject.csproj
           - dotnet test TestPressProject.csproj