language: csharp
mono: latest
dotnet: 3.1
solution: "Project 3 - Main/Project 3 - Press Project.sln"

jobs:
   include: 
     #- stage:  "build"
     #  Name: "Build core application on .NET Core 3.1"
     #  script: 
     #      - dotnet restore 'Project 3 - Main/Project 3 - Press Project.csproj'
     #      - dotnet build 'Project 3 - Main/Project 3 - Press Project.csproj'
     #- stage: "test"
     #  Name: "Test core application on .NET Core 3.1"
     #  script:
     #      - cd TestPressProject 
     #      - dotnet add package NUnit.Console
     #      - dotnet restore TestPressProject.csproj
     #      - dotnet build TestPressProject.csproj
     #      - dotnet test TestPressProject.csproj
     - stage: "qualimetry"
       sudo: required
       if: branch = sonar
       Name: "Build on .NET Core and send to sonar"
       before_script:          
          - wget -O sonar.zip https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.8.0.12008/sonar-scanner-msbuild-4.8.0.12008-netcoreapp3.0.zip
          - wget -O opencover.zip https://github.com/OpenCover/opencover/releases/download/4.7.922/opencover.4.7.922.zip
          - mkdir -p tools/{sonar,opencover} https://github.com/OpenCover/opencover/releases/download/4.7.922/opencover.4.7.922.zip
          - unzip -qq sonar.zip -d tools/sonar
          - unzip -qq opencover.zip -d tools/opencover
          - chmod 777 tools/ -R
       script:
         - dotnet tools/sonar/SonarScanner.MSBuild.dll begin /k:"kali-ci" /d:sonar.host.url="https://sonar.melo-mania.fr" /d:'sonar.cs.opencover.reportsPaths=opencover.xml' /d:sonar.login=99fc4397f326f81e6ff80646d0ad2571882bac1d
         - dotnet restore 'Project 3 - Main (Only NonUI for Travis).sln'
         - dotnet build 'Project 3 - Main (Only NonUI for Travis).sln' /t:Rebuild
         - mono tools/opencover/OpenCover.Console.Exe -target:"`which dotnet`" -targetargs:"test 'Project 3 - Main (Only NonUI for Travis).sln'"
         - curl -k https://melo-mania.fr/cert.pem --output trusted-sonar-instance.certificate.pem 
         - sudo keytool -importcert -file trusted-sonar-instance.certificate.pem -keystore $JAVA_HOME/lib/security/cacerts -noprompt -storepass changeit
         - dotnet tools/sonar/SonarScanner.MSBuild.dll end /d:sonar.login=99fc4397f326f81e6ff80646d0ad2571882bac1d
